[App]
port = 5000
image_folder = E:\AI\Output
max_initial_load = 100
logging_level = basic

# Grid Settings
home_thumbnail_columns_default = 3
gallery_thumbnail_size_default = 3
thumbnail_aspect_ratio = square

# Folders & Definitions
nsfw_folders = nsfw
safe_folders = SAFE
nsfw_keywords = adult, bikini, boob, booty, bra, bras, busty, breast, breasts, camgirl, camwhore, cleavage, curvy, dominatrix, escort, erotic, explicit, fetish, gstring, hardcore, hot girl, hot woman, intimate, kink, latex, leotard, lingerie, naked, nipple, nipples, nude, nudes, nsfw, onlyfans, panties, pantyhose, panty, playboy, porn, pornographic, pornstar, provocative, seductive, sensual, sex, sexually, softcore, stripper, suggestive, swimsuit, thong, topless, underwear, xxx, spycam, voyeur, spycam, peephole, pussy, voyeuristic
nsfw_labels = FEMALE_BREAST_EXPOSED, FEMALE_GENITALIA_EXPOSED, MALE_GENITALIA_EXPOSED, BUTTOCKS_EXPOSED, ANUS_EXPOSED, BELLY_EXPOSED, FEMALE_BREAST_COVERED

# Feature Toggles
metadata_extraction = true
hide_archive = false

# Keyword Filter Settings
enable_keyword_filter_option = true
keyword_filter_default = false
toggle_keyword_filter_passphrase = 

# Safe Only Settings
enable_safe_only_option = true
safe_only_default = false
toggle_safe_only_passphrase = 

# Folder Lock Settings
enable_content_lock_option = true
content_lock_default = false
toggle_content_lock_passphrase = 

# Content Scan Settings
enable_content_scan_option = true
content_scan_default = false
toggle_content_scan_passphrase = 
content_scan_offset = 0
nudity_threshold = 0.4
scan_video_files = true

# Security / Passphrases
delete_passphrase = 
flag_passphrase = 
archive_passphrase = 
settings_passphrase = 
